### ISSUE TITLE
create a user profile page

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#11]
A user profile page should allow:

* view registered API
* refresh API metadata via the registered URL
* delete API metadata

**Comment by marcodarko** [comment]
Dashboard added with the following features:

1. user information on the left panel with two basic actions ( add api and logout)
2. (first tab)  list of API contributions (animated delete and refresh buttons -with functional methods to be added soon, working on this)
3.  logout from dashboard
4. (second tab) access to API extensions information
5.(third tab) access to SmartAPI helpful resources (repo, spec, extensions, etc)
6. last refreshed timestamp
7. notifications when something has been refreshed or failed to refresh
8. deletion pops up a modal that requires user to verify the name of the API to be deleted in order to delete
9. expanded api details view on modal by clicking on API name

Additional Additions: 
Header - a user menu dropdown appears after login to give you access to your dashboard and possible future implementations that require login. 
Colors - changed to a darker look for header and footer to keep focus on main content.

**Comment by marcodarko** [comment]
Dashboard only available with user info after login, disappears if logged out. 
Index has new animated menus and animations fired by scrolling down.  
Parallax background. 

To-do:  implement delete and refresh methods to dashboard

**Comment by marcodarko** [comment]
Dashboard has been implemented ready for production!
User can view all contributions, search for specific api, refresh api and delete api (archived).
