### ISSUE TITLE
Add _id, _meta fields for /api/metadata/{smartapi_id} endpoint

### ISSUE THREAD

**Issue by kevinxin90** [SmartAPI/smartAPI#114]
Can we have more consistent behavior between /api/metadata/{smartapi_id} and /api/query endpoint.

For /api/query endpoint, each API spec returned has fields like _id, _meta, _status. However, these fields are missing in /api/metadata/{smartapi_id} endpoint, e.g. https://smart-api.info/api/metadata/5076f09382b38d56a77e376416b634ca

**Comment by namespacestd0** [comment]
This is a big topic worth in-depth discussion because SmartAPI's elasticsearch index is storing both application's internal data and full text query data, which also differs from the user submitted data. The annotation endpoint is actually not using biothings API's annotation handler but a separate one providing the feature to explicitly return what the user submitted. How we model the data at each handler and how they accommodate different use cases require further discussion. However, there's already a roadmap to enhance the functionalities in those areas.

**Comment by namespacestd0** [comment]
Solution validated as of commit 428e62d6ba58d63dfe392aaa9cf23bd97d05633b
