### ISSUE TITLE
add mychem.info mappings for rhea to the smartAPI annotation

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#123]
mychem.info provides mappings between chemicals and the rhea database.  For example, output for http://mychem.info/v1/query?q=chebi.id:CHEBI\:16169&fields=chebi.xrefs.rhea is shown below.  I would like to have have these xrefs annotated in the [SmartAPI annotation for mychem.info](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/openapi_full.yml). 

```
{
  "took": 2,
  "total": 1,
  "max_score": 9.790655,
  "hits": [
    {
      "_id": "IGMNYECMUMZDDF-UHFFFAOYSA-M",
      "_score": 9.790655,
      "chebi": {
        "_license": "http://bit.ly/2KAUCAm",
        "xrefs": {
          "rhea": [
            "RHEA:37975",
            "RHEA:22208",
            "RHEA:38003",
            "RHEA:15161",
            "RHEA:15157",
            "RHEA:22204",
            "RHEA:15449",
            "RHEA:16189",
            "RHEA:37995"
          ]
        }
      }
    }
  ]
}
```

related to: https://github.com/NCATSTranslator/testing/issues/49

**Comment by andrewsu** [comment]
@kevinxin90 the more I look at this, the more I'm worried about including Rhea IDs as an alternate ID for `ChemicalSubstance`s.  I think it might be better as a `MolecularActivity` (https://biolink.github.io/biolink-model/docs/MolecularActivity.html) that is `biolink:related_to` a `ChemicalSubstance`.  Each Rhea ID can have multiple chemical reactants/products.  For example, http://mychem.info/v1/query?q=chebi.xrefs.rhea:RHEA\:15161 returns three distinct chemical substances. If we add Rhea as a mapping, then wouldn't BTE treat those three compounds as equivalent?

**Comment by colleenXu** [comment]
Again, (1) we want to handle Rhea IDs correctly (not a chemical) and (2) we want the registry and everything set up for ChemicalSubstance <-> MolecularActivity (Rhea) operations in BTE

**Comment by colleenXu** [comment]
To clarify: something seems odd about how MyChem deals with Rhea:

* having chebi.xrefs.rhea is odd since the Rhea IDs are actually reactions that the various chemicals are involved in. Instead, I suggest having records under each chemical:
```
{
  _id: XXXXX,
  chebi: {}, 
  chembl: {},
  rhea: [
    {reaction_id: X},
    {reaction_id: Y}
  ]
}
``` 
* unichem.rhea seems to be **incorrect**; its value is just the CHEBI ID rather than a Rhea Reaction ID. See how this [record](https://mychem.info/v1/query?q=GZCGUPFRVQAUEE-SLPGGIOYSA-N) says that the unichem.rhea ID is 42758....this ID [does not correspond to a rhea reaction](https://www.rhea-db.org/rhea/42758) with the chemical inside. Instead, 42758 seems to be the CHEBI ID for this chemical..

**Comment by ravila4** [comment]
Perhaps these issues should be opened on MyChem.info repo. For the issue with chebi.xrefs.rhea, I'm not sure if it's an issue with the way the data is structured, or the way BTE handles the mapping.

The second problem with unichem.rhea does seem like something we may want to fix upstream on mychem.info. It is not a parsing error, because the original Unichem data  is linking to CHRBI compiund IDs instead of RHEA reaction ids:
https://www.ebi.ac.uk/unichem/frontpage/results?queryText=GZCGUPFRVQAUEE-SLPGGIOYSA-N&kind=InChIKey&sources=&incl=exclude
However, we can use the Chebi IDs to query RHEA directly: https://www.rhea-db.org/rhea/?query=CHEBI:42758&format=json

**Comment by colleenXu** [comment]
issue is now opened and we can discuss there @ravila4
