### ISSUE TITLE
incorrect "Updated" date?

### ISSUE THREAD

**Issue by andrewsu** [SmartAPI/smartAPI#167]
It seems like every entry in SmartAPI is reporting a last updated date of today.  I tested this pretty diverse cross section of APIs (some of which I _think_ are obsolete)...

* http://smart-api.info/registry?q=15bf82dcf5bdd2c95d8687250b662cbb
* https://smart-api.info/registry?q=219ac6646d0e2db862b533fb618db5b4
* https://smart-api.info/registry?q=34e351cb4eac8bc7dbacf55f1b5ce44b
* https://smart-api.info/registry?q=b0ead2b28cfe5794e24845661ba45897

![image](https://user-images.githubusercontent.com/2635409/168883401-df94a2c5-f33f-471c-ba3a-89b76851fd4a.png)

**Comment by andrewsu** [comment]
Bumping this issue since I think the last-updated date can be a very useful signal as to whether an API is current or not... (and because I'm thinking this might be a simple fix?)

**Comment by colleenXu** [comment]
I think "last updated" refers to the date/time of the last uptime / source link check.

But it's confusing because at first glance, it looks like "time since the source link / registration was substantially changed". I'm not sure what "substantially changed" means or how to evaluate it (whether a manual update / refresh is done? or monitoring of this link/registration?).
