### ISSUE TITLE
Feature request: Show tags on individual API pages

### ISSUE THREAD

**Issue by CaseyTa** [SmartAPI/smartAPI#203]
When searching the SmartAPI registry, the APIs listed in the search results have tags under the API name, like `TRAPI 1.4.0` and `Translator: KP`. Example from the search results page:
![image](https://github.com/SmartAPI/smartAPI/assets/32798737/779804ad-7265-44b5-90cd-1e17e56c838b)

But when viewing an API's documentation page, many of those tags are not visible. Example from the documentation page:
![image](https://github.com/SmartAPI/smartAPI/assets/32798737/9f3a3418-e03d-4e91-a456-1703f9e64daf)

It would be nice of those tags were visible from the API's documentation page.

**Comment by marcodarko** [comment]
Because the UI here is using Swagger UI it's hard to position them below the title but with a little CSS magic I can get them close above the title.  I wouldn't try to overlay them on top using CSS because I can't guarantee the same position for every browser.  Here's a pic, let me know if you have any suggestions or let me know what you think :) 

<img width="1181" alt="Screenshot 2023-09-07 at 3 23 40 PM" src="https://github.com/SmartAPI/smartAPI/assets/23092057/b491f75e-47a3-4486-948e-56821e9ac953">

**Comment by CaseyTa** [comment]
That's great! Thanks for implementing this and doing it at lightning speed!

**Comment by marcodarko** [comment]
FYI: It's not up yet but it will be included in our next update son hopefully!

**Comment by CaseyTa** [comment]
Understood, thanks again!
