### ISSUE TITLE
the list of operations (under "paths") should follow the order in the metadata

### ISSUE THREAD

**Issue by newgene** [SmartAPI/smartAPI#34]
The list of operations displayed in the registry should follow their order in the API metadata (under "paths").

This should be fixed at the backend and consider using OrderedDict for json deserialization:

https://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict
https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps

**Comment by namespacestd0** [comment]
Observed that 
	as of 12/11/2018, the production server
	1.  does not present the results in "Registry" page with the paths and their corresponding HTTP methods (under "operations" column) in the orders as they appeared in the original Metadata files,
	2. runs Python version 3.4.*,
	3. runs ElasticSearch 2.4.*. [2]

Understanding that
	1. the insertion-order preservation nature of "dict" objects in Python was _only_ declared to be an official part of the Python language spec on and presumably after version 3.7 released on June 27, 2018. [1]
	2. the paths are stored in an _ordered_ list of for each API in ES.
	3. the HTTP methods of each path are stored in an _unordered_ collection of name/value pairs in es.

I think it's likely that
	1. the orders of "paths" under "operations" of APIs are lost in (de)serialization in indexing to or querying from Elasticsearch.
	2. the orders of HTTP methods are never preserved (in ES).

Further examinations show that
	1. in the test environment installed with python 3.7 and Elasticsearch 6.5, api.es.ESQuery.refreshall() successfully updates the "paths" order to align with the order in original metadata. [3]
	2. the above command does _not_ correct the order of "HTTP methods" of each path.

It might be sufficient at this point to suggest that
	in order to resolve the issue:
	1. upgrade python to 3.7 on the production server, [4]
	2. a. modify the HTTP methods indexing scheme to preserve order, 
	     b. display the HTTP methods in a fixed order in front-end (preferred by @newgene)
	3. and then refresh APIs by retrieving the latest metadata file online 
        4. or re-index the archived copy if the API metadata link no longer works. [5]

[1] https://docs.python.org/3.7/whatsnew/3.7.html
[2] The Elasticsearch version may not be relevant to this issue. The test environment happens to have a newer es version preparing for future releases.
[3] For those APIs that contain valid URLs to retrieve the latest Metadata.
[4] Simply specifying "OrderedDict" as the type handled by python json library without upgrading python might not be sufficient to change the behavior because python Elasticsearch package uses encoding/decoding methods without type customization in multiple contexts. (e.g. elasticsearch/serializer.py)
[5] Multiple steps. It seems that there is no direct method provided a.t.m.

**Comment by newgene** [comment]
@namespacestd0 thanks for looking into this! Looks like this issue will be solved by running SmartAPI production in Python 3.7 and re-index all API metadata in Elasticsearch.

In particular, from https://docs.python.org/3.7/whatsnew/3.7.html, this is related to this issue:

> the insertion-order preservation nature of dict objects has been declared to be an official part of the Python language spec.

Let's leave this issue open for now. After we migrate our smartapi production to the new server (with Python 3.7 and ES6), let's verify it's working as expected and then close this issue.

**Comment by marcodarko** [comment]
Operations are properly viewed in original order https://smart-api.info/registry
