### ISSUE TITLE
Disabling OAuth in Developer Mode

### ISSUE THREAD

**Issue by nicholsn** [SmartAPI/smartAPI#41]
Is it possible to disable the requirement for OAuth when in developer mode?

For example, I'd like to run the SmartAPI app locally and login to test out adding new records without needing to authenticate with github's OAuth endpoint.

**Comment by namespacestd0** [comment]
Hi, Nicholsn,

Thank you for contacting us regarding your experience with setting up SmartAPI locally. I understand you are having trouble adding new records without authenticating with Github OAuth endpoint. That is indeed what is necessary to perform registry operations right now.

I shared your comments with other members of our team and we would like to suggest that you give it another try with this [newly revised instruction](https://github.com/SmartAPI/smartAPI/commit/1977f999767b785e650b21650fadd7539ba5f7d9?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) first. There are helpful messages now to explain how to point the Github authentication callback to your local development server. Since we consider multi-user support an integrated part of the SmartAPI registry and using Github OAuth would both benefit our users and to keep the program focused, we are not considering providing the option to disable this as of this moment.

We hope you find this explanation helpful, and if we may be of any further assistance please feel free to comment on this issue. The issue will be closed if this solves your problem or we do not hear back from you for 7 days.

Thank you,
Jerry

**Comment by nicholsn** [comment]
Thank you for the detailed response and for the updated instructions. I'll give this a try.
