### ISSUE TITLE
Request for data

### ISSUE THREAD

**Issue by webyrd** [SmartAPI/smartAPI#85]
Hello!

It would be super useful for Unsecret Agent to have access to the following data sources via SmartAPI:

STRING
National Clinical Drug Trials
REPODB

Thank you!

**Comment by kevinxin90** [comment]
@webyrd 
Hi Will, thanks for your interest! We're happy to provide these resources through SmartAPI.

By saying **National Clinical Drug Trials**, I suppose you are referring to [clinicaltrials.gov](https://clinicaltrials.gov/)? This is a huge dataset with lots of information for each trail, are there any fields/info which you are specifically interested in?

Thanks!
Kevin

**Comment by TriageDr** [comment]
Hi Kevin, 

Initial investigation of the source yields ~ 350k xml structures, 1 for each trial.  The XML structure for each trial varies widely depending on the trial's length, phase, whether the trial was completed and whether clinical results were posted. 

As for data size, the entire db is **1.62GB** zipped and can be downloaded here: **https://clinicaltrials.gov/ct2/resources/download**

Here is the link to the xml structure for all the clinical trial xml docs: **https://clinicaltrials.gov/ct2/html/images/info/public.xsd**  

I'm still working through the structures to identified specific fields for import!

**Comment by kevinxin90** [comment]
REPODB: https://unmtid-shinyapps.net/shiny/repodb/

**Comment by kevinxin90** [comment]
Proposed output structure for repodb.
Each document represent a unique drug using drugbank id as primary key(_id) (so all rows with the same drugbank ID should be grouped together).
One drug may have multiple indications, so they should be grouped together.
```
{
    "_id": "DB00879",
    "repodb": {
        "drugbank": "DB09477",
        "name": "enalapril",
        "indications": [
            {
                "name": "Hypertensive disease",
                "umls": "C0020538",
                "status": "NA",
                "phase": "NA"
                "detailed_status": "NA"
            },
            {
                "name": "Congestive heart failure",
                "umls": "C0018802",
                "status": "NA",
                "phase": "NA",
                "detailed_status": "NA",
            },
            ...
        ]
    }
}
```

**Comment by erikyao** [comment]
Example: Suppose we have the following entries in the repoDB csv.

| drug_name     | drugbank_id | ind_name                                           | ind_id   | NCT | status   | phase | DetailedStatus |
|---------------|-------------|----------------------------------------------------|----------|-----|----------|-------|----------------|
| enalapril     | DB00584     | Asymptomatic left ventricular systolic dysfunction | C3698411 | NA  | Approved | NA    | NA             |
| enalapril     | DB00584     | Hypertensive disease                               | C0020538 | NA  | Approved | NA    | NA             |

The expected output is:

```
{
    "_id": "DB00584",
    "repodb": {
        "drugbank": "DB00584",
        "name": "enalapril",
        "indications": [
            {
                "name": "Asymptomatic left ventricular systolic dysfunction",
                "umls": "C3698411",
                "NCT": "NA",
                "status": "Approved",
                "phase": "NA"
                "detailed_status": "NA"
            },
            {
                "name": "Hypertensive disease",
                "umls": "C0020538",
                "NCT": "NA",
                "status": "Approved",
                "phase": "NA"
                "detailed_status": "NA"
            }
        ]
    }
}
```

**Comment by erikyao** [comment]
Addendum (2020-11-05): we found a possible glitch in the original repoDB csv file that one drugbank ID
may correspond to multiple drug names. E.g. drugbank ID "DB00002" is found on the following entries:

| drug_name               | drugbank_id | ind_name                           | ind_id   | NCT         | status     | phase           | DetailedStatus                   |
|-------------------------|-------------|------------------------------------|----------|-------------|------------|-----------------|----------------------------------|
| cetuximab               | DB00002     | Squamous cell carcinoma of mouth   | C0585362 | NA          | Approved   | NA              | NA                               |
| cetuximab               | DB00002     | Squamous cell carcinoma of nose    | C3163899 | NA          | Approved   | NA              | NA                               |
| cetuximab               | DB00002     | Squamous cell carcinoma of pharynx | C1319317 | NA          | Approved   | NA              | NA                               |
| cetuximab               | DB00002     | Laryngeal Squamous Cell Carcinoma  | C0280324 | NA          | Approved   | NA              | NA                               |
| cetuximab               | DB00002     | Malignant tumor of colon           | C0007102 | NA          | Approved   | NA              | NA                               |
| NA                      | DB00002     | Non-Small Cell Lung Carcinoma      | C0007131 | NCT00203931 | Terminated | Phase 2         | Slow accrual and evidence...     |
| dexamethasone phosphate | DB00002     | Multiple Myeloma                   | C0026764 | NCT00368121 | Terminated | Phase 2         | Lack of recruitable patients     |
| cetuximab               | DB00002     | Non-Small Cell Lung Carcinoma      | C0007131 | NCT00694603 | Terminated | Phase 2         | Slow accrual                     |
| cetuximab               | DB00002     | Squamous cell carcinoma            | C0007137 | NCT01794845 | Terminated | Phase 2         | Early termination due to lack... |
| NA                      | DB00002     | Squamous cell carcinoma            | C0007137 | NCT02298595 | Withdrawn  | Phase 1/Phase 2 | NA                               |

It's not clear how NA was produced in the 1st column but for the 7th entry (dexamethasone phosphate), @kevinxin90 found it's actually a combo drug with cetuximab. 

To maintain the one-to-one relationship between `drug_name` and `drugbank_id`, here we apply the following policy:

- Discard the original `drug_name` column in the repoDB csv file
- Use mychem.info API to find a correct drug name for each drugbank ID

**Comment by erikyao** [comment]
Addendum (2020-11-06): we found that some drug bank IDs are not found in mychem.info (e.g. "DB12430")

To maintain the one-to-one relationship between `drug_name` and `drugbank_id`, here we apply the following policy:

- Temporarily discard the original `drug_name` column in the repoDB csv file
- Use mychem.info API to find a drug name for each drugbank ID
    - If not found, use the original `drug_name`
    - If the original `drug_name` is NA or not unique, manipulate manually

**Comment by erikyao** [comment]
API released at https://biothings.ncats.io/repodb

The web page seems to have a little glitch. @marcodarko is working on it.
